/**
 * Static list of valid Kafka topic extra config keys with their default values.
 * Keys are immutable — only values may be changed by users.
 */
export const KAFKA_EXTRA_CONFIG_DEFAULTS: Record<string, string> = {
    "compression.gzip.level": "-1",
    "compression.lz4.level": "9",
    "compression.type": "producer",
    "compression.zstd.level": "3",
    "confluent.cluster.link.allow.legacy.message.format": "false",
    "confluent.compacted.topic.prefer.tier.fetch.ms": "-1",
    "confluent.context.name": "",
    "confluent.key.schema.validation": "false",
    "confluent.key.subject.name.strategy": "io.confluent.kafka.serializers.subject.TopicNameStrategy",
    "confluent.log.cleaner.timestamp.validation.enable": "true",
    "confluent.max.segment.ms": "9223372036854775807",
    "confluent.min.segment.ms": "1",
    "confluent.placement.constraints": "",
    "confluent.prefer.tier.fetch.ms": "-1",
    "confluent.segment.speculative.prefetch.enable": "false",
    "confluent.stray.log.delete.delay.ms": "604800000",
    "confluent.stray.log.max.deletions.per.run": "72",
    "confluent.system.time.roll.enable": "false",
    "confluent.tier.cleaner.compact.min.efficiency": "0.5",
    "confluent.tier.cleaner.compact.segment.min.bytes": "20971520",
    "confluent.tier.cleaner.dual.compaction": "false",
    "confluent.tier.cleaner.enable": "false",
    "confluent.tier.cleaner.min.cleanable.ratio": "0.75",
    "confluent.tier.enable": "false",
    "confluent.tier.local.hotset.bytes": "-1",
    "confluent.tier.local.hotset.ms": "86400000",
    "confluent.tier.segment.hotset.roll.min.bytes": "104857600",
    "confluent.value.schema.validation": "false",
    "confluent.value.subject.name.strategy": "io.confluent.kafka.serializers.subject.TopicNameStrategy",
    "delete.retention.ms": "86400000",
    "file.delete.delay.ms": "60000",
    "flush.messages": "9223372036854775807",
    "flush.ms": "9223372036854775807",
    "follower.replication.throttled.replicas": "",
    "index.interval.bytes": "4096",
    "leader.replication.throttled.replicas": "",
    "local.retention.bytes": "-2",
    "local.retention.ms": "-2",
    "max.compaction.lag.ms": "9223372036854775807",
    "max.message.bytes": "1048588",
    "message.downconversion.enable": "true",
    "message.format.version": "3.0-IV1",
    "message.timestamp.after.max.ms": "9223372036854775807",
    "message.timestamp.before.max.ms": "9223372036854775807",
    "message.timestamp.difference.max.ms": "9223372036854775807",
    "message.timestamp.type": "CreateTime",
    "min.cleanable.dirty.ratio": "0.5",
    "min.compaction.lag.ms": "0",
    "preallocate": "false",
    "remote.storage.enable": "false",
    "retention.bytes": "-1",
    "segment.bytes": "1073741824",
    "segment.index.bytes": "10485760",
    "segment.jitter.ms": "0",
    "segment.ms": "604800000",
    "unclean.leader.election.enable": "false",
};
